### ISSUE TITLE
[BUG] Forked the repo and got Object is possibly 'null' in api/_lib/parser.ts

### ISSUE THREAD

**Issue by Snazzyham** [zeit/og-image#105]
I forked the repo as per the instructions in the README, and first ran into an issue where I couldn't `now dev` because my `codebase isn't linked to a project on ZEIT Now.`

I linked it, and then had to modify the `now.json` to reduce the memory to 1024 and remove the line with the regions set to `["all"]`. 

Once doing that, I was able to push up to Now but got a build error. When trying locally, I ran into an issue with the `pathname` declaration in `api/_lib/parser.ts`. 

Image attached below for reference. Perhaps I'm doing something wrong? 

![](https://images.prismic.io/snazzyham/efce60b8-c17a-4d85-a63a-2204a21798b9_Screenshot+2020-03-31+at+4.10.33+PM.png?auto=compress,format)

Also, if the above steps taken where necessary and not unique to just me, I'd love to help update the README. 

Thanks.

**Comment by Snazzyham** [comment]
Managed to fix this by adding replacing line 17 of `api/_lib/parser.ts` with `const arr = pathname!.slice(1).split(".")` 

Not sure if this was the right thing to do but I have 0 experience with TypeScript and this was a suggested answer on StackOverflow. 

Seems to be working kind of alright. The image URL I replaced in `getDefaultImages()` works, but toggling between different images that I defined in `web/index.ts` doesn't seem to work. Not an issue for me but might be for someone else. 

[here's a URL](https://og-image-5aj4qrfey.now.sh/) to my deploy if anyone wants to have a look.

**Comment by styfle** [comment]
Hi @Snazzyham 

> codebase isn't linked to a project on ZEIT Now

This is expected. The dev commands live in the cloud in [Project Settings](https://zeit.co/blog/advanced-project-settings).

> then had to modify the now.json to reduce the memory to 1024 and remove the line with the regions set to ["all"].

This is expected for Hobby accounts. If you want to use more memory or more regions, you'll need a paid account.

> pathname declaration in api/_lib/parser.ts.

It sounds like you deleted `yarn.lock` or modified the dependencies. A later version of `@types/node` added `null` as a return type when earlier versions didn't have it. I confirmed that deploying this project without modifying dependencies works without type errors.

**Comment by Snazzyham** [comment]
Ah yes, I used NPM instead of yarn, that must've been the source of my woes. Apologies. And thanks.

**Comment by styfle** [comment]
I'll update the dependencies at some point in the future when I upgrade to Node 12, but that will require more thorough testing since this project is used in production for https://zeit.co og images. Thanks 👍
