### ISSUE TITLE
Possibly change default settings in `now.json`

### ISSUE THREAD

**Issue by krzysztofzuraw** [zeit/og-image#107]
Hi 👋🏻
Thank you for this service - it is really awesome 🎉 . I have one suggestion - is it possible to change default settings in `now.json`? I have those two lines in mind:
https://github.com/zeit/og-image/blob/master/now.json#L2
https://github.com/zeit/og-image/blob/master/now.json#L7

Yesterday I tried to run `og-image` on my free Zeit account and I have to change those settings (`regions`, `memory`). If you want I can prepare PR with changes either to `now.json` or maybe to readme with description what needs to be changed if developer has a free account. I have a question about `memory` setting too - lowering it to 1024 will cause some problems in the long run?

**Comment by styfle** [comment]
Hi @krzysztofzuraw 

> maybe to readme with description what needs to be changed if developer has a free account

Yes, let's update the readme and mention that free accounts should remove all properties besides `rewrites` which is the only one necessary for this app to function properly.

**Comment by krzysztofzuraw** [comment]
Awesome - I can take it 😄
