### ISSUE TITLE
Enabling HTML_DEBUG

### ISSUE THREAD

**Issue by eriskhan** [zeit/og-image#115]
Hey there! I've been trying to enable environment variable HTML_DEBUG, but couldn't find any hooks on that. Could you please help with enabling it? Thanks!

**Comment by styfle** [comment]
Running `export OG_HTML_DEBUG=1` first

**Comment by eriskhan** [comment]
Unfortunately, that doesn't help at all. After running "setx OG_HTML_DEBUG "1" /m" nothing changed and og-images are still served as pictures, not HTML documents

**Comment by styfle** [comment]
You could try changing this line 

https://github.com/zeit/og-image/blob/9e4bc4f78fd55b12319427faa1374e8313f02ff7/api/index.ts#L7

```
const isHtmlDebug = true
```
