### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by j** [zeit/og-image#43]
I'm wondering that since you cache the page instance and don't close browsers/pages, what happens on concurrent requests?

**Comment by styfle** [comment]
That's a great question!

The code makes it seem like this would cause a problem but in practice, it works.

Here's an example that you might think would cause problems.

```js
Array.from({ length: 20 }).forEach((o, i) => {
  var url = `https://og-image.now.sh/concurrent%20${i}.png`;
  fetch(url).then(() => console.log('fetched complete for url ' + url))
});
```

But it works fine.

![image](https://user-images.githubusercontent.com/229881/52129066-98fdb800-2604-11e9-8191-512d711a567c.png)

I won't post a screenshot of all the results but I cycled through and they all had the correct number.

![image](https://user-images.githubusercontent.com/229881/52129116-b9c60d80-2604-11e9-8dcc-375cfd7079a0.png)

**Comment by j** [comment]
Well, that's scary.  Haha

**Comment by j** [comment]
I'm currently running chrome on lambda in production but having to create a new browser each request just because that's what every production post I've seen recommends.  I.e., what happens when Page crashes, etc.  A simple "launch" for each request and closing it no matter what (catching exceptions and closing, etc), is what I see for production uses... but it makes it a lot slower.  I was going to work on pooling browser instances and the pool would automatically start a browser to the specific page so that it's warm for each request. No one really knows how lambda truly works under high workload in AWS.  I see reports of zombie processes that end up exceeding lambda's limits and crashing, so I'm afraid when that hits, that lambda is done for.  Not sure though?

**Comment by j** [comment]
Looks like internally, Page's screenshots are added to a queue and the result of the chain is returned from the screenshot method.

**Comment by styfle** [comment]
Were you able to make it fail with concurrent requests and display the wrong response?

**Comment by styfle** [comment]
I'm going to close this since there have been no signs of any issue here. Let me know if you find something wrong 👍
