### ISSUE TITLE
Adding second image causes 500 error

### ISSUE THREAD

**Issue by styfle** [zeit/og-image#93]
## Steps to reproduce

Click "Add Image 2" on the latest deployment https://og-image-ratwvzitg.zeit.sh

## Details 

This regression was introduced in #87 when we moved to zero config.

It works correctly with `now dev` but not with `now`.

**Comment by styfle** [comment]
The problem can be narrowed down to `handle:filesystem`.

This one works:

```json
{
    "regions": ["all"],
    "public": true,
    "version": 2,
    "routes": [
        { "src": "/", "dest": "/index.html" },
        { "src": "/(favicon.ico|style.css|robots.txt)", "dest": "/$1" },
        { "src": "/dist/web/index.js", "dest": "/dist/web/index.js" },
        { "src": "/(.+)", "dest": "/api" }
    ]
}
```

This one does not work:

```json
{
    "regions": ["all"],
    "public": true,
    "version": 2,
    "routes": [
        { "handle": "filesystem" },
        { "src": "/(.+)", "dest": "/api" }
    ]
}
```

**Comment by leo** [comment]
Being tracked here now: https://github.com/zeit/now-proxy/issues/1273
