### ISSUE TITLE
Update docs re Node version

### ISSUE THREAD

**Issue by janklimo** [zeit/og-image#97]
Seems like this **must** use Node 8.10 because of [this dependency](https://github.com/alixaxel/chrome-aws-lambda#usage). Docs should mention that, painful to debug when upgrading to Node 10.

**Comment by styfle** [comment]
The node version is defined in the canonical package.json here: https://github.com/zeit/og-image/blob/master/package.json#L6

See the docs about defining engines here: https://docs.npmjs.com/files/package.json#engines

**Comment by janklimo** [comment]
@styfle I understand that. What I meant is that new users of the repo might think that Node version is outdated, bump it up, and then spend hours debugging what's wrong. I opened #98 with the proposed addition.
